# Generated by Django 6.1.1 on 2026-09-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_privacy_policy_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttoken',
            name='metadata',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='accounttoken',
            name='purpose',
            field=models.CharField(choices=[('email_verification', 'Weryfikacja email'), ('password_reset', 'Reset hasla'), ('password_change', 'Zmiana hasla'), ('email_change', 'Zmiana email')], max_length=32),
        ),
    ]
