# Generated by Django 6.1.1 on 2026-09-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accounttoken_metadata_user_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttoken',
            name='purpose',
            field=models.CharField(choices=[('email_verification', 'Weryfikacja email'), ('password_reset', 'Reset hasła'), ('password_change', 'Zmiana hasła'), ('email_change', 'Zmiana email'), ('account_deletion', 'Usunięcie konta')], max_length=32),
        ),
    ]
