# Generated by Django 6.1.1 on 2026-09-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_googleaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_paying_firm',
            field=models.BooleanField(default=False),
        ),
    ]
