# Generated by Django 6.1.1 on 2026-09-29 16:45

import apps.common.security
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_show_paying_firm'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security_hint_hidden_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TwoFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secret', models.TextField()),
                ('secret_key_id', models.CharField(blank=True, max_length=16)),
                ('last_step', models.BigIntegerField(default=0)),
                ('backup_codes', models.JSONField(default=list)),
                ('device_nonce', models.CharField(default=apps.common.security.generate_public_token, max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
