# Generated by Django 6.1.1 on 2026-09-28 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billingaccount_past_due_since_billingnotice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VatInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('stripe_mode', models.CharField(max_length=8)),
                ('stripe_invoice_id', models.CharField(max_length=64, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(max_length=255)),
                ('gross', models.PositiveIntegerField(help_text='Kwota brutto w groszach.')),
                ('paid_at', models.DateTimeField()),
                ('client', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Do wystawienia'), ('processing', 'Wystawiana w inFakt'), ('issued', 'Wystawiona'), ('failed', 'Błąd – wystaw ręcznie')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('infakt_mode', models.CharField(blank=True, max_length=8)),
                ('infakt_task', models.CharField(blank=True, db_index=True, max_length=64)),
                ('infakt_uuid', models.CharField(blank=True, max_length=64)),
                ('number', models.CharField(blank=True, max_length=64)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vat_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
    ]
