# Generated by Django 6.1.1 on 2026-09-28 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_vatinvoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('person', 'Osoba prywatna'), ('company', 'Firma')], default='person', max_length=8)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('tax_id', models.CharField(blank=True, max_length=32)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(max_length=255)),
                ('post_code', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='PL', max_length=2)),
                ('registry_name', models.CharField(blank=True, max_length=255)),
                ('registry_status', models.CharField(blank=True, max_length=32)),
                ('registry_checked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
