# Generated by Django 6.1.1 on 2026-09-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_billingprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='registry_source',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
