# Generated by Django 6.1.1 on 2026-09-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_billingprofile_registry_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='country',
            field=models.CharField(default='PL', editable=False, max_length=2),
        ),
    ]
