# Generated by Django 6.1.1 on 2026-09-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_billingprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaccount',
            name='trial_plan',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
