# Generated by Django 6.1.1 on 2026-09-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_billingaccount_trial_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='registry_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
