# Generated by Django 6.1.1 on 2026-09-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_billingprofile_registry_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaccount',
            name='credit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
