# Generated by Django 6.1.1 on 2026-09-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_billingaccount_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutconsent',
            name='documents',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
