# Generated by Django 6.1.1 on 2026-09-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_checkoutconsent_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatinvoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Do wystawienia'), ('processing', 'Wystawiana w inFakt'), ('issued', 'Wystawiona'), ('failed', 'Błąd - wystaw ręcznie')], db_index=True, default='pending', max_length=16),
        ),
    ]
