# Generated by Django 6.1.1 on 2026-09-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_alter_vatinvoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vatinvoice',
            name='infakt_client_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
