# Generated by Django 6.1.1 on 2026-09-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='kind',
            field=models.CharField(choices=[('manual', 'Ręczne'), ('automatic', 'Automatyczne')], max_length=16),
        ),
    ]
