# Generated by Django 6.1.1 on 2026-10-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_alter_reminder_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='kind',
            field=models.CharField(choices=[('manual', 'Ręczne'), ('automatic', 'Automatyczne'), ('deadline', 'Przed terminem')], max_length=16),
        ),
    ]
