#!/bin/sh
# Rewrites /etc/nginx/snippets/cloudflare-real-ip.conf from Cloudflare's
# published address lists and reloads nginx. Keeps the old file if the
# lists can't be fetched or nginx rejects the new one. Run as root, e.g.
# monthly from cron:
#   0 4 1 * * /srv/monituj/deploy/nginx/update-cloudflare-ips.sh
set -eu

TARGET=/etc/nginx/snippets/cloudflare-real-ip.conf
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

V4=$(curl -fsS --max-time 20 https://www.cloudflare.com/ips-v4)
V6=$(curl -fsS --max-time 20 https://www.cloudflare.com/ips-v6)
[ -n "$V4" ] && [ -n "$V6" ] || { echo "Empty list from Cloudflare" >&2; exit 1; }

{
  echo "# Generated by update-cloudflare-ips.sh on $(date -u +%F) - do not edit."
  echo "# The visitor's real address from Cloudflare's header, trusted only on"
  echo "# requests that come from Cloudflare's own addresses."
  for net in $V4 $V6; do
    echo "set_real_ip_from $net;"
  done
  echo "real_ip_header CF-Connecting-IP;"
} > "$TMP"

mkdir -p /etc/nginx/snippets
[ -f "$TARGET" ] && cp "$TARGET" "$TARGET.bak"
install -m 644 "$TMP" "$TARGET"
if nginx -t 2>/dev/null; then
  systemctl reload nginx
  echo "Updated $TARGET"
else
  [ -f "$TARGET.bak" ] && mv "$TARGET.bak" "$TARGET"
  echo "nginx rejected the new list - old one kept" >&2
  exit 1
fi
