# Generated by Django 5.1.15 on 2026-09-22 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_key', models.CharField(max_length=255, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=127)),
                ('size', models.PositiveBigIntegerField()),
                ('checksum', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('uploaded', 'Przeslany'), ('accepted', 'Zaakceptowany'), ('rejected', 'Odrzucony')], default='uploaded', max_length=32)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_email', models.EmailField(blank=True, max_length=254)),
                ('submitted_note', models.TextField(blank=True)),
                ('uploaded_by_session_key', models.CharField(blank=True, max_length=64)),
                ('request_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='requests.requestitem')),
            ],
            options={
                'indexes': [models.Index(fields=['request_item', 'status'], name='documents_d_request_de83ae_idx')],
            },
        ),
    ]
