# Generated by Django 6.1.1 on 2026-09-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='case_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
