# Generated by Django 6.1.1 on 2026-09-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_case_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUploadThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_hash', models.CharField(max_length=64)),
                ('upload_date', models.DateField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ip_hash', 'upload_date'), name='unique_anonymous_upload_per_day')],
            },
        ),
    ]
