# Generated by Django 6.1.1 on 2026-09-23 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_anonymousuploadthrottle'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='anonymousuploadthrottle',
            name='unique_anonymous_upload_per_day',
        ),
        migrations.DeleteModel(
            name='AnonymousUploadThrottle',
        ),
        migrations.RemoveField(
            model_name='document',
            name='case_reference',
        ),
        migrations.RemoveField(
            model_name='document',
            name='submitted_email',
        ),
        migrations.RemoveField(
            model_name='document',
            name='submitted_note',
        ),
    ]
