# Generated by Django 6.1.1 on 2026-09-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_anonymousuploadthrottle_unique_anonymous_upload_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
