# Generated by Django 6.1.1 on 2026-09-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_anonymized_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Przesłany'), ('accepted', 'Zaakceptowany'), ('rejected', 'Odrzucony')], default='uploaded', max_length=32),
        ),
    ]
