# Generated by Django 6.1.1 on 2026-09-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='encryption_key_id',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='document',
            name='wrapped_key',
            field=models.TextField(blank=True),
        ),
    ]
