# Generated by Django 5.1.15 on 2026-09-22 14:06

import apps.common.security
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('public_token', models.CharField(default=apps.common.security.generate_public_token, editable=False, max_length=64, unique=True)),
                ('reminders_enabled', models.BooleanField(default=True)),
                ('first_reminder_after_days', models.PositiveSmallIntegerField(default=2)),
                ('reminder_frequency_days', models.PositiveSmallIntegerField(default=3)),
                ('max_reminders', models.PositiveSmallIntegerField(default=3)),
                ('reminder_send_hour', models.PositiveSmallIntegerField(default=9)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='clients.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordProtectedAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_protected_access', to='requests.request')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('brak', 'Brak'), ('w_trakcie', 'W trakcie'), ('dostarczony', 'Dostarczony'), ('zaakceptowany', 'Zaakceptowany'), ('odrzucony', 'Odrzucony')], default='brak', max_length=32)),
                ('rejection_reason', models.TextField(blank=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='requests.request')),
            ],
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['client'], name='requests_re_client__efba88_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['public_token'], name='requests_re_public__b488e3_idx'),
        ),
        migrations.AddIndex(
            model_name='requestitem',
            index=models.Index(fields=['request', 'status'], name='requests_re_request_0a68b1_idx'),
        ),
    ]
