# Generated by Django 6.1.1 on 2026-09-23 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_anonymousrequestthrottle'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='retention_days',
            field=models.PositiveSmallIntegerField(default=90, help_text='How long uploaded files are kept before anonymization.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
    ]
