# Generated by Django 6.1.1 on 2026-09-24 10:42

import apps.common.security
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_request_retention_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token', models.CharField(default=apps.common.security.generate_public_token, editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='awaiting_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='confirmation_token',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='request',
            name='pending_access_password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
