# Generated by Django 6.1.1 on 2026-09-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_recipientaccess_request_awaiting_confirmation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='reminder_send_hour',
        ),
        migrations.AddField(
            model_name='recipientaccess',
            name='timezone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='request',
            name='sender_timezone',
            field=models.CharField(default='Europe/Warsaw', max_length=64),
        ),
    ]
