# Generated by Django 6.1.1 on 2026-09-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_remove_request_reminder_send_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='invitation_queued',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
