# Generated by Django 6.1.1 on 2026-09-29 11:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('requests', '0006_request_invitation_queued'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('item_names', models.JSONField(default=list)),
                ('interval', models.CharField(choices=[('daily', 'Codziennie'), ('weekly', 'Co tydzień'), ('biweekly', 'Co 2 tygodnie'), ('monthly', 'Co miesiąc')], default='monthly', max_length=16)),
                ('month_day', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('weekday', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(6)])),
                ('anchor_on', models.DateField(blank=True, null=True)),
                ('workdays_only', models.BooleanField(default=True)),
                ('deadline_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('deadline_month_day', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('reminders_enabled', models.BooleanField(default=True)),
                ('first_reminder_after_days', models.PositiveSmallIntegerField(default=2)),
                ('reminder_frequency_days', models.PositiveSmallIntegerField(default=3)),
                ('max_reminders', models.PositiveSmallIntegerField(default=3)),
                ('retention_days', models.PositiveSmallIntegerField(default=90, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('active', models.BooleanField(default=True)),
                ('next_due_on', models.DateField()),
                ('next_run_on', models.DateField(db_index=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.JSONField(blank=True, default=dict)),
                ('clients', models.ManyToManyField(related_name='recurring_requests', to='clients.client')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_run_on', 'id'],
            },
        ),
        migrations.AddField(
            model_name='request',
            name='recurring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='requests.recurringrequest'),
        ),
    ]
