# Generated by Django 6.1.1 on 2026-09-30 09:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_recurring_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('item_names', models.JSONField(default=list)),
                ('deadline_choice', models.CharField(default='14', max_length=8)),
                ('deadline_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reminders_enabled', models.BooleanField(default=True)),
                ('first_reminder_after_days', models.PositiveSmallIntegerField(default=2)),
                ('reminder_frequency_days', models.PositiveSmallIntegerField(default=3)),
                ('max_reminders', models.PositiveSmallIntegerField(default=3)),
                ('retention_days', models.PositiveSmallIntegerField(default=90, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title', 'id'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'title'), name='unique_template_title_per_owner')],
            },
        ),
    ]
