# Generated by Django 6.1.1 on 2026-10-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0008_request_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='not_applicable_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='not_applicable_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='status',
            field=models.CharField(choices=[('brak', 'Brak'), ('w_trakcie', 'W trakcie'), ('dostarczony', 'Dostarczony'), ('zaakceptowany', 'Zaakceptowany'), ('odrzucony', 'Odrzucony'), ('nie_dotyczy', 'Nie dotyczy')], default='brak', max_length=32),
        ),
    ]
