# Generated by Django 6.1.1 on 2026-09-24 14:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('version', models.CharField(max_length=32)),
                ('choices', models.JSONField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegalAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(choices=[('regulamin', 'Regulamin'), ('umowa_powierzenia', 'Umowa powierzenia przetwarzania danych'), ('polityka_prywatnosci', 'Polityka prywatności')], max_length=32)),
                ('version', models.CharField(max_length=64)),
                ('method', models.CharField(choices=[('rejestracja', 'Rejestracja (email i hasło)'), ('google', 'Rejestracja przez Google'), ('prosba_bez_konta', 'Prośba bez konta'), ('aktualizacja', 'Akceptacja nowej wersji')], max_length=32)),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accepted_at', '-id'],
                'indexes': [models.Index(fields=['user', 'document', 'version'], name='consents_le_user_id_75f465_idx')],
            },
        ),
        migrations.CreateModel(
            name='LegalUpdateNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=64)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_update_notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'version'), name='one_legal_notice_per_version')],
            },
        ),
    ]
