# Generated by Django 6.1.1 on 2026-09-29 06:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalupdatenotice',
            name='version',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='LegalVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(db_index=True, max_length=32)),
                ('version', models.CharField(max_length=10)),
                ('sha256', models.CharField(max_length=64)),
                ('html', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'wersja dokumentu',
                'verbose_name_plural': 'wersje dokumentów',
                'ordering': ['document', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('document', 'sha256'), name='one_row_per_wording')],
            },
        ),
        migrations.AddField(
            model_name='legalacceptance',
            name='wording',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='consents.legalversion'),
        ),
    ]
