# Generated by Django 6.1.1 on 2026-09-30 14:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0002_legal_versions'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announced', models.CharField(max_length=255, unique=True)),
                ('changes', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
