# Generated by Django 6.1.1 on 2026-10-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0003_legal_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalannouncement',
            name='changes',
        ),
    ]
