# Generated by Django 6.1.1 on 2026-10-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0004_remove_legalannouncement_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalacceptance',
            name='method',
            field=models.CharField(choices=[('rejestracja', 'Rejestracja (email i hasło)'), ('google', 'Rejestracja przez Google'), ('prosba_bez_konta', 'Prośba bez konta'), ('aktualizacja', 'Akceptacja nowej wersji'), ('zaproszenie_do_zespolu', 'Dołączenie do zespołu')], max_length=32),
        ),
    ]
