# Generated by Django 5.1.15 on 2026-09-22 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('USER_REGISTERED', 'User registered'), ('USER_LOGIN', 'User login'), ('USER_LOGIN_FAILED', 'User login failed'), ('PASSWORD_CHANGED', 'Password changed'), ('CLIENT_CREATED', 'Client created'), ('CLIENT_UPDATED', 'Client updated'), ('REQUEST_CREATED', 'Request created'), ('REQUEST_UPDATED', 'Request updated'), ('DOCUMENT_UPLOADED', 'Document uploaded'), ('DOCUMENT_ACCEPTED', 'Document accepted'), ('DOCUMENT_REJECTED', 'Document rejected'), ('REMINDER_SENT', 'Reminder sent'), ('PUBLIC_LINK_ACCESSED', 'Public link accessed'), ('PASSWORD_ACCESS_FAILED', 'Password access failed'), ('FILE_DOWNLOAD', 'File download'), ('FILE_DELETED', 'File deleted')], max_length=64)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'created_at'], name='audit_audit_event_07f862_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_4c2ead_idx')],
            },
        ),
    ]
