# Generated by Django 5.1.15 on 2026-09-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event',
            field=models.CharField(choices=[('USER_REGISTERED', 'User registered'), ('USER_LOGIN', 'User login'), ('USER_LOGIN_FAILED', 'User login failed'), ('USER_LOGOUT', 'User logout'), ('EMAIL_VERIFIED', 'Email verified'), ('PASSWORD_CHANGED', 'Password changed'), ('CLIENT_CREATED', 'Client created'), ('CLIENT_UPDATED', 'Client updated'), ('REQUEST_CREATED', 'Request created'), ('REQUEST_UPDATED', 'Request updated'), ('DOCUMENT_UPLOADED', 'Document uploaded'), ('DOCUMENT_ACCEPTED', 'Document accepted'), ('DOCUMENT_REJECTED', 'Document rejected'), ('REMINDER_SENT', 'Reminder sent'), ('PUBLIC_LINK_ACCESSED', 'Public link accessed'), ('PASSWORD_ACCESS_FAILED', 'Password access failed'), ('FILE_DOWNLOAD', 'File download'), ('FILE_DELETED', 'File deleted')], max_length=64),
        ),
    ]
