# Generated by Django 6.1.1 on 2026-09-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_alter_auditlog_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event',
            field=models.CharField(choices=[('USER_REGISTERED', 'User registered'), ('USER_LOGIN', 'User login'), ('USER_LOGIN_FAILED', 'User login failed'), ('USER_LOGOUT', 'User logout'), ('EMAIL_VERIFIED', 'Email verified'), ('PASSWORD_CHANGED', 'Password changed'), ('PASSWORD_CHANGE_REQUESTED', 'Password change requested'), ('EMAIL_CHANGE_REQUESTED', 'Email change requested'), ('EMAIL_CHANGED', 'Email changed'), ('PROFILE_UPDATED', 'Profile updated'), ('CLIENT_CREATED', 'Client created'), ('CLIENT_UPDATED', 'Client updated'), ('CLIENT_DELETED', 'Client deleted'), ('REQUEST_CREATED', 'Request created'), ('REQUEST_UPDATED', 'Request updated'), ('INVITATION_SENT', 'Invitation sent'), ('DOCUMENT_UPLOADED', 'Document uploaded'), ('DOCUMENT_ACCEPTED', 'Document accepted'), ('DOCUMENT_REJECTED', 'Document rejected'), ('REMINDER_SENT', 'Reminder sent'), ('PUBLIC_LINK_ACCESSED', 'Public link accessed'), ('PASSWORD_ACCESS_FAILED', 'Password access failed'), ('FILE_DOWNLOAD', 'File download'), ('FILE_DELETED', 'File deleted'), ('DOCUMENTS_ANONYMIZED', 'Documents anonymized'), ('REQUEST_CLOSED', 'Request closed'), ('REQUEST_REOPENED', 'Request reopened'), ('ACCOUNT_DELETION_REQUESTED', 'Account deletion requested'), ('GOOGLE_LINKED', 'Google sign-in linked'), ('GOOGLE_UNLINKED', 'Google sign-in unlinked')], max_length=64),
        ),
    ]
