# Generated by Django 5.1.15 on 2026-09-22 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('template', models.CharField(choices=[('zaproszenie', 'Zaproszenie'), ('przypomnienie', 'Przypomnienie'), ('potwierdzenie_uploadu', 'Potwierdzenie uploadu'), ('komplet_dokumentow', 'Komplet dokumentow'), ('odrzucenie', 'Odrzucenie'), ('weryfikacja_email', 'Weryfikacja email'), ('reset_hasla', 'Reset hasla')], max_length=32)),
                ('status', models.CharField(choices=[('sent', 'Wyslany'), ('failed', 'Blad')], max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='requests.request')),
            ],
            options={
                'indexes': [models.Index(fields=['recipient_email', 'template'], name='notificatio_recipie_bf5c5a_idx')],
            },
        ),
    ]
