# Generated by Django 6.1.1 on 2026-09-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='template',
            field=models.CharField(choices=[('zaproszenie', 'Zaproszenie'), ('przypomnienie', 'Przypomnienie'), ('potwierdzenie_uploadu', 'Potwierdzenie uploadu'), ('komplet_dokumentow', 'Komplet dokumentow'), ('odrzucenie', 'Odrzucenie'), ('weryfikacja_email', 'Weryfikacja email'), ('reset_hasla', 'Reset hasla'), ('haslo_dostepu', 'Haslo dostepu')], max_length=32),
        ),
    ]
