# Generated by Django 6.1.1 on 2026-09-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_emaillog_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='template',
            field=models.CharField(choices=[('zaproszenie', 'Zaproszenie'), ('przypomnienie', 'Przypomnienie'), ('potwierdzenie_uploadu', 'Potwierdzenie uploadu'), ('komplet_dokumentow', 'Komplet dokumentow'), ('odrzucenie', 'Odrzucenie'), ('weryfikacja_email', 'Weryfikacja email'), ('reset_hasla', 'Reset hasla'), ('haslo_dostepu', 'Haslo dostepu'), ('potwierdzenie_zmiany_hasla', 'Potwierdzenie zmiany hasla'), ('haslo_zmienione', 'Haslo zmienione'), ('potwierdzenie_zmiany_email', 'Potwierdzenie zmiany email'), ('prosba_zmiany_email', 'Prosba o zmiane email'), ('email_zmieniony', 'Email zmieniony'), ('anonimizacja_wlasciciel', 'Anonimizacja (wlasciciel)'), ('anonimizacja_odbiorca', 'Anonimizacja (odbiorca)')], max_length=32),
        ),
    ]
