# Generated by Django 6.1.1 on 2026-09-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_emaillog_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('sent', 'Wyslany'), ('failed', 'Blad'), ('skipped', 'Pominiety (demo)')], max_length=16),
        ),
    ]
