# Generated by Django 6.1.1 on 2026-09-24 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_status'),
        ('notifications', '0008_alter_emaillog_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='template',
            field=models.CharField(choices=[('zaproszenie', 'Zaproszenie'), ('przypomnienie', 'Przypomnienie'), ('potwierdzenie_uploadu', 'Potwierdzenie uploadu'), ('komplet_dokumentow', 'Komplet dokumentów'), ('odrzucenie', 'Odrzucenie'), ('weryfikacja_email', 'Weryfikacja email'), ('reset_hasla', 'Reset hasła'), ('haslo_dostepu', 'Hasło dostępu'), ('potwierdzenie_zmiany_hasla', 'Potwierdzenie zmiany hasła'), ('haslo_zmienione', 'Hasło zmienione'), ('potwierdzenie_zmiany_email', 'Potwierdzenie zmiany email'), ('prosba_zmiany_email', 'Prośba o zmianę email'), ('email_zmieniony', 'Email zmieniony'), ('anonimizacja_wlasciciel', 'Anonimizacja (właściciel)'), ('anonimizacja_odbiorca', 'Anonimizacja (odbiorca)'), ('potwierdzenie_usuniecia_konta', 'Potwierdzenie usunięcia konta'), ('konto_usuniete', 'Konto usunięte'), ('prosba_anulowana', 'Prośba anulowana'), ('potwierdzenie_prosby', 'Potwierdzenie prośby bez konta'), ('dostep_do_panelu', 'Dostęp do panelu bez hasła'), ('komplet_wlasciciel', 'Komplet dokumentów (nadawca)'), ('kontakt_wiadomosc', 'Formularz kontaktowy'), ('kontakt_potwierdzenie', 'Formularz kontaktowy (potwierdzenie)'), ('dokument_dodany', 'Nowy dokument (nadawca)')], max_length=32),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('dokument_dodany', 'Dodano dokument')], default='dokument_dodany', max_length=32)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'read_at'], name='notificatio_user_id_47e85c_idx'), models.Index(fields=['emailed_at'], name='notificatio_emailed_9898f3_idx')],
            },
        ),
    ]
