# Generated by Django 6.1.1 on 2026-09-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_emaillog_template_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='template',
            field=models.CharField(choices=[('zaproszenie', 'Zaproszenie'), ('przypomnienie', 'Przypomnienie'), ('potwierdzenie_uploadu', 'Potwierdzenie uploadu'), ('komplet_dokumentow', 'Komplet dokumentów'), ('odrzucenie', 'Odrzucenie'), ('weryfikacja_email', 'Weryfikacja email'), ('reset_hasla', 'Reset hasła'), ('haslo_dostepu', 'Hasło dostępu'), ('potwierdzenie_zmiany_hasla', 'Potwierdzenie zmiany hasła'), ('haslo_zmienione', 'Hasło zmienione'), ('potwierdzenie_zmiany_email', 'Potwierdzenie zmiany email'), ('prosba_zmiany_email', 'Prośba o zmianę email'), ('email_zmieniony', 'Email zmieniony'), ('anonimizacja_wlasciciel', 'Anonimizacja (właściciel)'), ('anonimizacja_odbiorca', 'Anonimizacja (odbiorca)'), ('potwierdzenie_usuniecia_konta', 'Potwierdzenie usunięcia konta'), ('konto_usuniete', 'Konto usunięte'), ('prosba_anulowana', 'Prośba anulowana'), ('potwierdzenie_prosby', 'Potwierdzenie prośby bez konta'), ('dostep_do_panelu', 'Dostęp do panelu bez hasła'), ('komplet_wlasciciel', 'Komplet dokumentów (nadawca)'), ('kontakt_wiadomosc', 'Formularz kontaktowy'), ('kontakt_potwierdzenie', 'Formularz kontaktowy (potwierdzenie)'), ('dokument_dodany', 'Nowy dokument (nadawca)'), ('google_polaczone', 'Logowanie Google dodane'), ('google_odlaczone', 'Logowanie Google odłączone'), ('google_potwierdz', 'Potwierdzenie połączenia z Google')], max_length=32),
        ),
    ]
