# Generated by Django 6.1.1 on 2026-10-01 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_encryption_key_id_document_wrapped_key'),
        ('notifications', '0021_alter_emaillog_template_reviewinvite'),
        ('requests', '0009_requestitem_not_applicable_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='request_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='requests.requestitem'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('dokument_dodany', 'Dodano dokument'), ('nie_dotyczy', 'Klient nie ma dokumentu')], default='dokument_dodany', max_length=32),
        ),
    ]
